<?php
//
//namespace Dastiii\Crawlers\Tests;
//
//use Dastiii\Crawlers\ObiDeCrawler;
//use Orchestra\Testbench\TestCase;
//use Dastiii\Crawlers\CrawlersServiceProvider;
//
//class ExampleTest extends TestCase
//{
//    protected $crawler;
//
//    public function setUp(): void
//    {
//        parent::setUp(); // TODO: Change the autogenerated stub
//
//        ObiDeCrawler::setStoreNumber(278);
//        $this->crawler = (new ObiDeCrawler('https://www.obi.de/search/6615397'));
//    }
//
//    /** @test */
//    public function it_can_get_a_products_name()
//    {
//        $this->assertEquals('Sakret Tiefengrund 5 l', $this->crawler->getProductName());
//    }
//
//
//}

//beforeEach(function () {
//    \Dastiii\Crawlers\ObiDeCrawler::setStoreNumber(278);
//
//    $this->crawler = new \Dastiii\Crawlers\ObiDeCrawler('https://www.obi.de/search/6615397');
//});

beforeEach(fn() => \Dastiii\Crawlers\ObiDeCrawler::setStoreNumber(278));

it('can get all of a 6615397 information', function () {
    $crawler = new \Dastiii\Crawlers\ObiDeCrawler('https://www.obi.de/search/6615397');

    expect($crawler->getProductName())->toBe('Sakret Tiefengrund 5 l');
    expect($crawler->getProductPrice())->toBe('44,99');
    expect($crawler->getProductNumber())->toBe('6615397');
    expect($crawler->getProductInStorePlacement())->toBe('Putz, Mörtel, Zement, Gang 27');
    expect($crawler->getProductDescription())->toContain('Artikelbeschreibung');
    expect($crawler->getProductImageUrl())->toBe('//images.obi.de/product/DE/415x415/661539_1.jpg');
    expect($crawler->getDatasheets())->toHaveLength(1);
});

it('can get all of 6939854 information', function () {
    $crawler = new \Dastiii\Crawlers\ObiDeCrawler('https://www.obi.de/search/6939854');

    expect($crawler->getProductName())->toBe('Knauf Tiefengrund LF 5 l');
    expect($crawler->getProductPrice())->toBe('29,99');
    expect($crawler->getProductNumber())->toBe('6939854');
    expect($crawler->getProductInStorePlacement())->toBe('Fliesenchemie & Werkzeuge, Gang 40; Putz, Mörtel, Zement, Gang 27');
    expect($crawler->getProductDescription())->toContain('Artikelbeschreibung');
    expect($crawler->getProductImageUrl())->toBe('//images.obi.de/product/DE/415x415/693985_2.jpg');
    expect($crawler->getDatasheets())->toHaveLength(1);
});
//
