<?php
//
//namespace Dastiii\Crawlers\Tests;
//
//use Dastiii\Crawlers\ObiDeCrawler;
//use Orchestra\Testbench\TestCase;
//use Dastiii\Crawlers\CrawlersServiceProvider;
//
//class ExampleTest extends TestCase
//{
//    protected $crawler;
//
//    public function setUp(): void
//    {
//        parent::setUp(); // TODO: Change the autogenerated stub
//
//        ObiDeCrawler::setStoreNumber(278);
//        $this->crawler = (new ObiDeCrawler('https://www.obi.de/search/6615397'));
//    }
//
//    /** @test */
//    public function it_can_get_a_products_name()
//    {
//        $this->assertEquals('Sakret Tiefengrund 5 l', $this->crawler->getProductName());
//    }
//
//
//}

beforeEach(function () {
    \Dastiii\Crawlers\ObiDeCrawler::setStoreNumber(278);

    $this->crawler = new \Dastiii\Crawlers\ObiDeCrawler('https://www.obi.de/search/6615397');
});

it('can get a products name', fn() => expect($this->crawler->getProductName())->toBe('Sakret Tiefengrund 5 l'));
it('can get a products price', fn() => expect($this->crawler->getProductPrice())->toBeString());
it('can get a products number', fn() => expect($this->crawler->getProductNumber())->toBe('6615397'));
it('can get a products in-store placement', fn() => expect($this->crawler->getProductInStorePlacement())->toBeString());
it('can get a products description', fn() => expect($this->crawler->getProductDescription())->toBeString());
it('can get a products image url', fn() => expect($this->crawler->getProductImageUrl())->toBeString());
it('can get a products datasheets', fn() => expect($this->crawler->getDatasheets())->not()->toBeEmpty());
